"""Configuration for the OpenAlex paper downloader."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

SEARCH_TERMS = [
    # Artificial Intelligence / Computer Science
    "computer science",
    "artificial intelligence",
    "machine learning",
    "deep learning",
    "reinforcement learning",
    "natural language processing",
    "computational linguistics",
    "computer vision",
    "speech recognition",
    "speech processing",
    "information retrieval",
    "recommender systems",
    "knowledge representation",
    "expert systems",
    "automated reasoning",
    "theorem proving",
    "planning and scheduling",
    "multi-agent systems",
    "artificial life",
    "evolutionary computation",
    "genetic algorithms",
    "swarm intelligence",
    "pattern recognition",
    "data mining",
    "data science",
    "statistical learning",
    "computational intelligence",
    "human-computer interaction",
    "human-robot interaction",
    "computer graphics",
    "image processing",
    "signal processing",
    "cybersecurity",
    "cryptography",
    "distributed computing",
    "parallel computing",
    "high performance computing",
    "cloud computing",
    "operating systems",
    "computer networks",
    "databases",
    "software engineering",
    "programming languages",
    "formal methods",
    "algorithms and data structures",
    "large language models",
    "transformers",
    "generative artificial intelligence",
    "generative models",
    "foundation models",
    "multimodal learning",
    "representation learning",
    "self-supervised learning",
    "semi-supervised learning",
    "unsupervised learning",
    "supervised learning",
    "transfer learning",
    "meta-learning",
    "federated learning",
    "continual learning",
    "reinforcement learning",
    "robotics",
    "autonomous systems",
    "autonomous vehicles",
    "edge computing",
    "internet of things",
    "computer architecture",
    "embedded systems",

    # Mathematics
    "mathematics",
    "pure mathematics",
    "applied mathematics",
    "discrete mathematics",
    "calculus",
    "differential equations",
    "partial differential equations",
    "ordinary differential equations",
    "real analysis",
    "complex analysis",
    "functional analysis",
    "abstract algebra",
    "group theory",
    "number theory",
    "topology",
    "geometry",
    "algebraic geometry",
    "combinatorics",
    "graph theory",
    "mathematical logic",
    "set theory",
    "category theory",
    "dynamical systems",
    "mathematical modeling",
    "operations research",
    "game theory",
    "information theory",
    "control theory",
    "optimization",
    "convex optimization",
    "stochastic processes",
    "probability theory",
    "statistics",
    "Bayesian statistics",
    "mathematical statistics",
    "numerical analysis",
    "linear algebra",
    "numerical methods",
    "statistical inference",
    "causal inference",
    "Bayesian inference",
    "Monte Carlo methods",
    "mathematical physics",

    # Physics
    "physics",
    "theoretical physics",
    "experimental physics",
    "quantum physics",
    "quantum mechanics",
    "quantum field theory",
    "quantum information",
    "quantum computing",
    "particle physics",
    "high energy physics",
    "nuclear physics",
    "atomic physics",
    "molecular physics",
    "condensed matter physics",
    "solid state physics",
    "statistical physics",
    "thermodynamics",
    "optics",
    "photonics",
    "plasma physics",
    "fluid dynamics",
    "classical mechanics",
    "electrodynamics",
    "gravitational physics",
    "general relativity",
    "astrophysics",
    "cosmology",
    "computational physics",
    "biophysics",
    "medical physics",
    "particle astrophysics",
    "astronomy",
    "planetary science",
    "solar physics",
    "space physics",
    "nuclear astrophysics",
    "quantum optics",
    "quantum information theory",
    "superconductivity",
    "nanophysics",

    # Chemistry
    "chemistry",
    "analytical chemistry",
    "organic chemistry",
    "inorganic chemistry",
    "physical chemistry",
    "theoretical chemistry",
    "computational chemistry",
    "biochemistry",
    "medicinal chemistry",
    "pharmaceutical chemistry",
    "polymer chemistry",
    "supramolecular chemistry",
    "electrochemistry",
    "photochemistry",
    "spectroscopy",
    "catalysis",
    "chemical kinetics",
    "surface chemistry",
    "materials chemistry",
    "nanochemistry",
    "environmental chemistry",
    "chemical thermodynamics",
    "chemical physics",
    "synthetic chemistry",
    "coordination chemistry",
    "organometallic chemistry",

    # Biology
    "biology",
    "biochemistry",
    "molecular biology",
    "cell biology",
    "microbiology",
    "bacteriology",
    "virology",
    "immunology",
    "genetics",
    "genomics",
    "epigenetics",
    "proteomics",
    "metabolomics",
    "bioinformatics",
    "computational biology",
    "systems biology",
    "structural biology",
    "developmental biology",
    "evolutionary biology",
    "ecology",
    "marine biology",
    "neuroscience",
    "neurobiology",
    "physiology",
    "anatomy",
    "zoology",
    "botany",
    "plant biology",
    "synthetic biology",
    "biotechnology",
    "molecular genetics",
    "population genetics",
    "microbial genetics",
    "genome biology",
    "transcriptomics",
    "metagenomics",
    "systems genetics",
    "cellular biology",
    "developmental genetics",
    "evolutionary genetics",
    "conservation biology",
    "biodiversity",
    "ecological modeling",
    "marine ecology",

    # Medicine / Health
    "medicine",
    "clinical medicine",
    "biomedical research",
    "biomedical engineering",
    "pathology",
    "pharmacology",
    "toxicology",
    "oncology",
    "cardiology",
    "neurology",
    "psychiatry",
    "endocrinology",
    "gastroenterology",
    "nephrology",
    "pulmonology",
    "infectious diseases",
    "dermatology",
    "pediatrics",
    "geriatrics",
    "surgery",
    "radiology",
    "anesthesiology",
    "emergency medicine",
    "nursing",
    "dentistry",
    "veterinary medicine",
    "epidemiology",
    "public health",
    "global health",
    "health policy",
    "health economics",
    "medical imaging",
    "clinical trials",
    "precision medicine",
    "pharmacogenomics",
    "medical genetics",
    "medical genomics",
    "regenerative medicine",
    "tissue engineering",
    "stem cell research",
    "translational medicine",
    "infectious disease research",
    "immunotherapy",
    "cancer research",
    "neuroscience",
    "clinical psychology",
    "nutrition science",

    # Engineering
    "engineering",
    "aerospace engineering",
    "aeronautical engineering",
    "automotive engineering",
    "biomedical engineering",
    "chemical engineering",
    "civil engineering",
    "computer engineering",
    "electrical engineering",
    "electronics engineering",
    "mechanical engineering",
    "materials engineering",
    "nuclear engineering",
    "environmental engineering",
    "industrial engineering",
    "manufacturing engineering",
    "systems engineering",
    "structural engineering",
    "transportation engineering",
    "telecommunications engineering",
    "control engineering",
    "robotics engineering",
    "mechatronics",
    "petroleum engineering",
    "energy engineering",
    "renewable energy",
    "semiconductor engineering",
    "microelectronics",
    "nanotechnology",
    "microfabrication",
    "chemical process engineering",
    "thermal engineering",
    "power engineering",
    "automotive systems",
    "aerospace systems",
    "structural mechanics",
    "fluid mechanics",
    "computational engineering",
    "finite element method",
    "computational fluid dynamics",
    "engineering optimization",

    # Earth / Environmental Sciences
    "earth science",
    "geoscience",
    "geology",
    "geophysics",
    "geochemistry",
    "mineralogy",
    "petrology",
    "paleontology",
    "seismology",
    "volcanology",
    "hydrology",
    "oceanography",
    "atmospheric science",
    "meteorology",
    "climatology",
    "climate science",
    "environmental science",
    "environmental engineering",
    "ecology",
    "conservation biology",
    "biodiversity",
    "soil science",
    "forestry",
    "agriculture",
    "agronomy",
    "environmental chemistry",
    "environmental pollution",
    "sustainability",
    "renewable energy",
    "climate change",
    "planetary science",
    "glaciology",
    "limnology",
    "hydrogeology",
    "environmental modeling",
    "natural hazards",
    "earth system science",
    "remote sensing",
    "geographic information systems",

    # Social Sciences
    "social science",
    "anthropology",
    "cultural anthropology",
    "archaeology",
    "human geography",
    "geography",
    "demography",
    "communication studies",
    "media studies",
    "journalism",
    "education",
    "educational psychology",
    "linguistics",
    "sociology",
    "political science",
    "international relations",
    "public policy",
    "public administration",
    "economics",
    "behavioral economics",
    "econometrics",
    "finance",
    "accounting",
    "management",
    "business administration",
    "marketing",
    "organizational behavior",
    "labor economics",
    "development economics",
    "political economy",
    "social psychology",
    "urban studies",
    "urban planning",
    "migration studies",
    "population studies",
    "gender studies",
    "development studies",
    "international development",
    "social policy",
    "social statistics",
    "computational social science",

    # Psychology / Cognitive Science
    "psychology",
    "cognitive psychology",
    "developmental psychology",
    "social psychology",
    "behavioral science",
    "cognitive science",
    "neuroscience",
    "computational neuroscience",
    "neuropsychology",
    "psycholinguistics",
    "behavioral economics",
    "perception",
    "memory",
    "learning theory",
    "decision making",
    "consciousness",
    "human cognition",
    "cognitive neuroscience",
    "experimental psychology",
    "clinical psychology",
    "personality psychology",
    "educational psychology",
    "organizational psychology",
    "behavioral science",
    "social cognition",
    "language cognition",

    # Humanities
    "humanities",
    "philosophy",
    "ethics",
    "epistemology",
    "metaphysics",
    "logic",
    "philosophy of science",
    "philosophy of mind",
    "philosophy of language",
    "aesthetics",
    "history",
    "ancient history",
    "medieval history",
    "modern history",
    "economic history",
    "history of science",
    "history of technology",
    "archaeology",
    "classics",
    "literature",
    "literary criticism",
    "comparative literature",
    "linguistics",
    "language studies",
    "cultural studies",
    "religious studies",
    "mythology",
    "art history",
    "musicology",
    "film studies",
    "theatre studies",
    "history of medicine",
    "history of mathematics",
    "history of philosophy",
    "intellectual history",
    "cultural history",
    "digital humanities",
    "folklore",
    "rhetoric",

    # Law / Politics / Governance
    "law",
    "constitutional law",
    "international law",
    "criminal law",
    "civil law",
    "corporate law",
    "intellectual property",
    "environmental law",
    "human rights",
    "legal theory",
    "jurisprudence",
    "political theory",
    "international relations",
    "geopolitics",
    "public policy",
    "public administration",
    "political economy",
    "governance",
    "international security",
    "security studies",
    "conflict studies",
    "peace studies",
    "constitutional theory",
    "legal philosophy",
    "criminal justice",
    "cyber law",
    "technology law",
    "health law",
    "international human rights law",

    # Business / Economics / Finance
    "economics",
    "macroeconomics",
    "microeconomics",
    "econometrics",
    "development economics",
    "behavioral economics",
    "international economics",
    "monetary economics",
    "financial economics",
    "finance",
    "corporate finance",
    "financial markets",
    "banking",
    "accounting",
    "auditing",
    "management",
    "business",
    "entrepreneurship",
    "marketing",
    "operations management",
    "supply chain management",
    "organizational behavior",
    "human resources",
    "strategy",
    "business analytics",
    "financial economics",
    "international finance",
    "investment",
    "asset pricing",
    "risk management",
    "financial econometrics",
    "development finance",
    "public finance",
    "labor economics",
    "health economics",
    "environmental economics",
    "industrial organization",
    "economic policy",

    # Interdisciplinary Sciences
    "computational science",
    "computational social science",
    "computational biology",
    "computational neuroscience",
    "computational linguistics",
    "scientific computing",
    "information science",
    "systems science",
    "complex systems",
    "network science",
    "systems theory",
    "decision science",
    "operations research",
    "interdisciplinary research",
    "science and technology studies",
    "bioinformatics",
    "digital humanities",
    "human-computer interaction",
    "cognitive science",
    "data science",
    "information theory",
    "complexity science",
    "network theory",
    "systems biology",
    "systems engineering",
    "mathematical modeling",
    "scientific machine learning",
    "AI for science",
    "machine learning for science",
    "computational mathematics",
    "computational chemistry",
    "computational physics",
    "computational materials science",
    "computational medicine",

    # Materials / Nanoscience
    "materials science",
    "materials engineering",
    "nanoscience",
    "nanotechnology",
    "nanomaterials",
    "2D materials",
    "graphene",
    "semiconductor materials",
    "composite materials",
    "ceramic materials",
    "metallic materials",
    "polymer science",
    "biomaterials",
    "smart materials",
    "electronic materials",
    "photonic materials",
    "energy materials",
    "battery materials",
    "materials characterization",

    # Energy
    "energy science",
    "energy engineering",
    "renewable energy",
    "solar energy",
    "solar power",
    "wind energy",
    "hydropower",
    "geothermal energy",
    "bioenergy",
    "nuclear energy",
    "nuclear power",
    "energy storage",
    "battery technology",
    "fuel cells",
    "hydrogen energy",
    "energy systems",
    "smart grids",
    "power systems",
    "energy efficiency",
    "carbon capture",
    "carbon sequestration",

    # Agriculture / Food
    "agriculture",
    "agronomy",
    "crop science",
    "plant science",
    "plant breeding",
    "soil science",
    "horticulture",
    "agricultural engineering",
    "precision agriculture",
    "agricultural biotechnology",
    "food science",
    "food technology",
    "food chemistry",
    "food microbiology",
    "nutrition",
    "animal science",
    "livestock science",
    "fisheries science",
    "aquaculture",
    "agricultural economics",
    "agricultural sustainability",

    # Astronomy / Space
    "astronomy",
    "astrophysics",
    "cosmology",
    "planetary science",
    "planetary geology",
    "space science",
    "space physics",
    "solar physics",
    "stellar astrophysics",
    "galactic astronomy",
    "exoplanets",
    "astrobiology",
    "gravitational waves",
    "black holes",
    "neutron stars",
    "dark matter",
    "dark energy",
    "early universe",
    "observational astronomy",

    # Core Scientific Methods
    "scientific computing",
    "numerical simulation",
    "computer simulation",
    "mathematical modeling",
    "statistical modeling",
    "probabilistic modeling",
    "causal inference",
    "statistical inference",
    "Bayesian inference",
    "Monte Carlo simulation",
    "optimization",
    "numerical optimization",
    "machine learning",
    "data analysis",
    "statistical analysis",
    "experimental design",
    "meta-analysis",
    "systematic review",
    "scientific methodology",
    "research methodology",
    "measurement science",
]

DEFAULT_ALLOWED_LICENSES: tuple[str, ...] = (
    "cc-by",
    "cc-by-sa",
    "cc0",
    "public-domain",
)

DEFAULT_SEARCH_TERMS = tuple(SEARCH_TERMS)

@dataclass
class DownloadConfig:
    """User-tunable settings for one corpus-download run.

    Attributes:
        api_key: OpenAlex API key.
        output_dir: Root folder papers/metadata/state are written into.
        search_terms: Search queries to run against the OpenAlex API.
        min_year: Earliest publication year to accept.
        min_citations: Minimum citation count to accept.
        max_papers_per_term: Maximum candidate papers kept per search term.
        max_downloads_per_day: Daily PDF-download ceiling.
        download_workers: Number of parallel download threads.
        request_timeout: HTTP request timeout, in seconds.
        max_retries: Retry attempts for transient (5xx/network) failures.
        allowed_licenses: Licenses that are accepted; empty means "any".
        user_agent: User-Agent header sent with every HTTP request.
    """

    api_key: str = ""
    output_dir: Path = field(default_factory=lambda: Path("research-corpus"))
    search_terms: tuple[str, ...] = DEFAULT_SEARCH_TERMS
    min_year: int = 2015
    min_citations: int = 10
    max_papers_per_term: int = 100
    max_downloads_per_day: int = 100
    download_workers: int = 6
    request_timeout: int = 60
    max_retries: int = 2
    allowed_licenses: tuple[str, ...] = DEFAULT_ALLOWED_LICENSES
    user_agent: str = (
        "TinyLLMResearchCorpus/1.0 (open-access research corpus builder)"
    )

    @property
    def papers_dir(self) -> Path:
        """Return the folder downloaded PDFs are stored in."""
        return self.output_dir / "papers"

    @property
    def metadata_dir(self) -> Path:
        """Return the folder per-paper metadata JSON files are stored in."""
        return self.output_dir / "metadata"

    @property
    def state_dir(self) -> Path:
        """Return the folder the daily download-counter state lives in."""
        return self.output_dir / "state"

    @property
    def manifest_file(self) -> Path:
        """Return the path of the successful-downloads manifest."""
        return self.output_dir / "manifest.jsonl"

    @property
    def failed_file(self) -> Path:
        """Return the path of the failed-downloads log."""
        return self.output_dir / "failed.jsonl"

    @property
    def state_file(self) -> Path:
        """Return the path of the daily download-counter state file."""
        return self.state_dir / "download_state.json"

    def ensure_directories(self) -> None:
        """Create the papers/metadata/state folders if missing."""
        self.papers_dir.mkdir(parents=True, exist_ok=True)
        self.metadata_dir.mkdir(parents=True, exist_ok=True)
        self.state_dir.mkdir(parents=True, exist_ok=True)
